apiVersion: v1
kind: ReplicationController
metadata:
  name: doosratakeapp
spec:
  replicas: 3
  selector:
    app: doosratakeapp  
  template:
    metadata:
      name: doosratakeapp
      labels:
        app: doosratakeapp
    spec:
      containers:
      - name: flask
        image: gcr.io/doosra-take/flask:v23
        ports:
        - containerPort: 5000
     
      